import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import Script from "next/script";
import FedaPayLoader from "@/components/payment/FedapayLoader";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Projet Y — Une vision en construction",
  description:
    "Découvrez l'histoire, la vision et l'évolution d'une aventure technologique en construction.",
  keywords: [
    "innovation",
    "technologie",
    "aventure",
    "communauté",
    "prototype",
  ],
};



// export const metadata: Metadata = {
//   title: "Projet Y — Une vision en construction",
//   description:
//     "Découvrez l'histoire, la vision et l'évolution d'une aventure technologique en construction.",

//   keywords: [
//     "innovation",
//     "technologie",
//     "aventure",
//     "communauté",
//     "prototype",
//   ],

//   icons: {
//     icon: "/icon/projet_Y.png",
//     shortcut: "/icon/projet_Y.png",
//     apple: "/icon/projet_Y.png",
//   },

//   openGraph: {
//     title: "Projet Y — Une vision en construction",
//     description:
//       "Découvrez l'histoire, la vision et l'évolution d'une aventure technologique en construction.",
//     images: [
//       {
//         url: "/icon/projet_Y.png",
//         width: 512,
//         height: 512,
//         alt: "Projet Y",
//       },
//     ],
//   },

//   twitter: {
//     card: "summary_large_image",
//     title: "Projet Y — Une vision en construction",
//     description:
//       "Découvrez l'histoire, la vision et l'évolution d'une aventure technologique en construction.",
//     images: ["/icon/projet_Y.png"],
//   },
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="fr">

      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#09090B] text-white antialiased`}
      >

        <Navbar />

        <main className="min-h-screen pt-20">
          {children}
        </main>

        <Footer />


      </body>

    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
